name:                rest-api-servant
version:             0.1.0
author:              "Normen Müller"
maintainer:          "normen.mueller@gmail.com"
copyright:           "(c) 2022 Normen Müller"
extra-source-files:
  - README.md
  - HISTORY.md
dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - http-media
  - lucid
  - semver
  - servant
  - servant-lucid
  - servant-server
  - text
  - time
  - transformers
  - wai
  - warp
library:
  source-dirs: src
executables:
  rest-api-servant-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    # cf. https://github.com/commercialhaskell/stack/issues/5439
    when:
      - condition: false
        other-modules: Paths_rest-api-servant
    dependencies:
      - rest-api-servant
tests:
  rest-api-servant-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - rest-api-servant
